# Generated by Django 5.2.17 on 2026-09-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("cardio", "Cardio"),
                    ("hiit", "HIIT"),
                    ("mobility", "Mobility"),
                    ("other", "Other"),
                ],
                default="strength",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DailyMacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("calories", models.PositiveIntegerField()),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_macros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="one_macro_log_per_user_per_day"
                    )
                ],
            },
        ),
    ]
