# Generated by Django 5.0.6 on 2026-10-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_exercise_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setentry",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sets",
                to="tracker.exercise",
            ),
        ),
    ]
